---
version: "3"
services:
  devnetsandbox:
    build:
      context: .
      dockerfile: dockerfile
    image: howdareyou82/devnetsandbox:latest
    volumes:
    - "$LOCALWORKDIR:/CODE:rw"
    network_mode: "bridge"
    container_name: dnsb